### ISSUE TITLE
Assembly resolving not working with type provider

### ISSUE THREAD

**Issue by DanielFabian** [tpetricek/FSharp.Formatting#139]
We use FSharp.Data for some of our processing. Since FSharp.Data is referenced in our project, I assume FSharp.Formatting pulls in the dependency. This should be ok, since it is also part of the build output. However, FSharp.Formatting also tries to pull in FSharp.Data.DesignTime which is **not** part of the build output. I added the path to FSharp.Data.DesignTime from the NuGet packages directory to the libDirs when calling the MetadataFormat.Generate call, but it still fails with the following error:

    [17:20:37] :     [Step 2/2] Generating index.html ...
    [17:20:37] :     [Step 2/2] Generating proview-index.html ...
    [17:20:37] :     [Step 2/2] Generating reference-index.html ...
    [17:20:39] :     [Step 2/2] [0 sec] Reading assembly: C:\BuildAgent\work\9cca5f94ac237474\results\InCube.Base.dll
    [17:20:39] :     [Step 2/2] [0 sec] Parsing assembly
    [17:20:39] :     [Step 2/2] [0 sec] Starting razor engine
    [17:20:39] :     [Step 2/2] [0 sec] Generating: index.html
    [17:20:39] :     [Step 2/2] [0 sec] Resolving assembly: System.Web.Razor.resources, Version=2.0.0.0, Culture=en-GB, PublicKeyToken=31bf3856ad364e35
    [17:20:39] :     [Step 2/2] [0 sec] Resolving assembly: System.Web.Razor.resources, Version=2.0.0.0, Culture=en-GB, PublicKeyToken=31bf3856ad364e35
    [17:20:39] :     [Step 2/2] [0 sec] Resolving assembly: System.Web.Razor.resources, Version=2.0.0.0, Culture=en, PublicKeyToken=31bf3856ad364e35
    [17:20:39] :     [Step 2/2] [0 sec] Resolving assembly: System.Web.Razor.resources, Version=2.0.0.0, Culture=en, PublicKeyToken=31bf3856ad364e35
    [17:20:39] :     [Step 2/2] [0 sec] Generating modules...
    [17:20:39] :     [Step 2/2] [0 sec] Generating module: incube-base-array2d
    [17:20:39] :     [Step 2/2] [0 sec] Generating module: incube-base-lensmodule
    [17:20:39] :     [Step 2/2] [0 sec] Generating module: incube-base-lensmodule-operators
    [17:20:39] :     [Step 2/2] [0 sec] Generating module: incube-base-iceutils
    [17:20:39] :     [Step 2/2] [0 sec] Generating module: incube-base-lensmodule-stateoperators
    [17:20:40] :     [Step 2/2] [1 sec] Finished module: incube-base-lensmodule-operators
    [17:20:40] :     [Step 2/2] [1 sec] Finished module: incube-base-lensmodule-stateoperators
    [17:20:40] :     [Step 2/2] [1 sec] Finished module: incube-base-array2d
    [17:20:40] :     [Step 2/2] [1 sec] Finished module: incube-base-lensmodule
    [17:20:40] :     [Step 2/2] [1 sec] Finished module: incube-base-iceutils
    [17:20:40] :     [Step 2/2] [1 sec] Generating types...
    [17:20:40] :     [Step 2/2] [1 sec] Generating type: incube-base-iceutils-servicebase
    [17:20:40] :     [Step 2/2] [1 sec] Generating type: incube-base-iceutils-iceboximplementationforattribute
    [17:20:40] :     [Step 2/2] [1 sec] Generating type: incube-base-lens-2
    [17:20:41] :     [Step 2/2] [2 sec] Finished type: incube-base-iceutils-iceboximplementationforattribute
    [17:20:41] :     [Step 2/2] [2 sec] Finished type: incube-base-lens-2
    [17:20:41] :     [Step 2/2] [2 sec] Finished type: incube-base-iceutils-servicebase
    [17:20:41] :     [Step 2/2] [2 sec] Reading assembly: C:\BuildAgent\work\9cca5f94ac237474\results\ProView.Dsl.dll
    [17:20:41] :     [Step 2/2] [2 sec] Parsing assembly
    [17:20:41] :     [Step 2/2] [2 sec] Starting razor engine
    [17:20:41] :     [Step 2/2] [2 sec] Generating: index.html
    [17:20:41] :     [Step 2/2] [2 sec] Generating modules...
    [17:20:41] :     [Step 2/2] [2 sec] Generating module: proview-dsl-syntax
    [17:20:41] :     [Step 2/2] [2 sec] Generating module: proview-dsl-evaluation
    [17:20:41] :     [Step 2/2] [2 sec] Generating module: proview-dsl-syntax-statistics
    [17:20:42] :     [Step 2/2] [3 sec] Finished module: proview-dsl-syntax-statistics
    [17:20:42] :     [Step 2/2] [3 sec] Finished module: proview-dsl-syntax
    [17:20:42] :     [Step 2/2] [3 sec] Finished module: proview-dsl-evaluation
    [17:20:42] :     [Step 2/2] [3 sec] Generating types...
    [17:20:42] :     [Step 2/2] [3 sec] Generating type: proview-dsl-evaluation-observations
    [17:20:42] :     [Step 2/2] [3 sec] Generating type: proview-dsl-evaluation-restrictedsymboltable
    [17:20:42] :     [Step 2/2] [3 sec] Generating type: proview-dsl-evaluation-statistic
    [17:20:42] :     [Step 2/2] [3 sec] Generating type: proview-dsl-syntax-binaryoperator
    [17:20:42] :     [Step 2/2] [3 sec] Generating type: proview-dsl-evaluation-symboltable
    [17:20:42] :     [Step 2/2] [3 sec] Generating type: proview-dsl-syntax-binarystatistictype
    [17:20:42] :     [Step 2/2] [3 sec] Generating type: proview-dsl-syntax-constraint
    [17:20:42] :     [Step 2/2] [3 sec] Generating type: proview-dsl-syntax-distribution
    [17:20:42] :     [Step 2/2] [3 sec] Generating type: proview-dsl-syntax-identifier
    [17:20:43] :     [Step 2/2] [4 sec] Generating type: proview-dsl-syntax-observationtype
    [17:20:43] :     [Step 2/2] [4 sec] Finished type: proview-dsl-syntax-observationtype
    [17:20:43] :     [Step 2/2] [4 sec] Generating type: proview-dsl-syntax-randomvariableexpression
    [17:20:43] :     [Step 2/2] [4 sec] Finished type: proview-dsl-syntax-distribution
    [17:20:43] :     [Step 2/2] [4 sec] Generating type: proview-dsl-syntax-statexproperator
    [17:20:43] :     [Step 2/2] [4 sec] Finished type: proview-dsl-syntax-identifier
    [17:20:43] :     [Step 2/2] [4 sec] Generating type: proview-dsl-syntax-statistic
    [17:20:43] :     [Step 2/2] [4 sec] Finished type: proview-dsl-evaluation-statistic
    [17:20:43] :     [Step 2/2] [4 sec] Generating type: proview-dsl-syntax-statisticexpression
    [17:20:43] :     [Step 2/2] [4 sec] Finished type: proview-dsl-syntax-constraint
    [17:20:43] :     [Step 2/2] [4 sec] Generating type: proview-dsl-syntax-statistictype
    [17:20:43] :     [Step 2/2] [4 sec] Finished type: proview-dsl-evaluation-symboltable
    [17:20:43] :     [Step 2/2] [4 sec] Finished type: proview-dsl-syntax-binarystatistictype
    [17:20:43] :     [Step 2/2] [4 sec] Finished type: proview-dsl-syntax-binaryoperator
    [17:20:44] :     [Step 2/2] [4 sec] Finished type: proview-dsl-evaluation-restrictedsymboltable
    [17:20:44] :     [Step 2/2] [4 sec] Finished type: proview-dsl-evaluation-observations
    [17:20:44] :     [Step 2/2] [5 sec] Finished type: proview-dsl-syntax-statistictype
    [17:20:44] :     [Step 2/2] [5 sec] Finished type: proview-dsl-syntax-randomvariableexpression
    [17:20:45] :     [Step 2/2] [5 sec] Finished type: proview-dsl-syntax-statexproperator
    [17:20:45] :     [Step 2/2] [5 sec] Finished type: proview-dsl-syntax-statistic
    [17:20:45] :     [Step 2/2] [5 sec] Finished type: proview-dsl-syntax-statisticexpression
    [17:20:45] :     [Step 2/2] [6 sec] **** warning: The type provider 'C:\BuildAgent\work\9cca5f94ac237474\results\FSharp.Data.dll' reported an error: Assembly attribute 'TypeProviderAssemblyAttribute' refers to a designer assembly 'FSharp.Data.DesignTime' which cannot be loaded or doesn't exist. Could not load file or assembly 'file:///C:\BuildAgent\work\9cca5f94ac237474\results\FSharp.Data.DesignTime.dll' or one of its dependencies. The system cannot find the file specified.
    [17:20:45] :     [Step 2/2] [6 sec] **** error: Referenced assembly 'C:\BuildAgent\work\9cca5f94ac237474\results\FSharp.Data.dll' has assembly level attribute 'Microsoft.FSharp.Core.CompilerServices.TypeProviderAssemblyAttribute' but no public type provider classes were found
    [17:20:45] :     [Step 2/2] [6 sec] Reading assembly: C:\BuildAgent\work\9cca5f94ac237474\results\ProView.FileReader.dll
    [17:20:45] :     [Step 2/2] [6 sec] Parsing assembly
    [17:20:45]W:     [Step 2/2] Running build failed.
    [17:20:45]W:     [Step 2/2] Error:
    [17:20:45]W:     [Step 2/2] Microsoft.FSharp.Compiler.ErrorLogger+ReportedError: Exception of type 'Microsoft.FSharp.Compiler.Tast+InternalUndefinedItemRef' was thrown.
    [17:20:45]W:     [Step 2/2]    at Microsoft.FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ErrorLogger.Error[b](ErrorLogger x, Exception exn) in C:\GitHub\fsharp\FSharp.Compiler.Service\src\fsharp\ErrorLogger.fs:line 329
    [17:20:45]W:     [Step 2/2]    at Microsoft.FSharp.Compiler.Tast.EntityRef.get_Deref() in C:\GitHub\fsharp\FSharp.Compiler.Service\src\fsharp\tast.fs:line 2549
    [17:20:45]W:     [Step 2/2]    at Microsoft.FSharp.Compiler.SourceCodeServices.FSharpEntity.get_LogicalName() in C:\GitHub\fsharp\FSharp.Compiler.Service\src\fsharp\vs\Typed.fs:line 91
    [17:20:45]W:     [Step 2/2]    at FSharp.MetadataFormat.ValueReader.|MeasureProd|_|(FSharpType typ) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 180
    [17:20:45]W:     [Step 2/2]    at FSharp.MetadataFormat.ValueReader.formatTypeWithPrec(Int32 prec, FSharpType typ) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 228
    [17:20:45]W:     [Step 2/2]    at FSharp.MetadataFormat.ValueReader.formatTypeApplication[a](String typeName, Int32 prec, Boolean prefix, FSharpList`1 args) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 211
    [17:20:45]W:     [Step 2/2]    at FSharp.MetadataFormat.ValueReader.formatTypeWithPrec(Int32 prec, FSharpType typ) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 239
    [17:20:45]W:     [Step 2/2]    at FSharp.MetadataFormat.ValueReader.retType@340.Invoke(FSharpType typ) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 340
    [17:20:45] :     [Step 2/2] ##teamcity[buildStatus status='FAILURE' text='Microsoft.FSharp.Compiler.ErrorLogger+ReportedError: Exception of type |'Microsoft.FSharp.Compiler.Tast+InternalUndefinedItemRef|' was thrown.   at Microsoft.FSharp.Compiler.ErrorLogger.ErrorLoggerExtensions.ErrorLogger.Error|[b|](ErrorLogger x, Exception exn) in C:\GitHub\fsharp\FSharp.Compiler.Service\src\fsharp\ErrorLogger.fs:line 329   at Microsoft.FSharp.Compiler.Tast.EntityRef.get_Deref() in C:\GitHub\fsharp\FSharp.Compiler.Service\src\fsharp\tast.fs:line 2549   at Microsoft.FSharp.Compiler.SourceCodeServices.FSharpEntity.get_LogicalName() in C:\GitHub\fsharp\FSharp.Compiler.Service\src\fsharp\vs\Typed.fs:line 91   at FSharp.MetadataFormat.ValueReader.||MeasureProd||_||(FSharpType typ) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 180   at FSharp.MetadataFormat.ValueReader.formatTypeWithPrec(Int32 prec, FSharpType typ) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 228   at FSharp.MetadataFormat.ValueReader.formatTypeApplication|[a|](String typeName, Int32 prec, Boolean prefix, FSharpList`1 args) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 211   at FSharp.MetadataFormat.ValueReader.formatTypeWithPrec(Int32 prec, FSharpType typ) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 239   at FSharp.MetadataFormat.ValueReader.retType@340.Invoke(FSharpType typ) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 340   at Microsoft.FSharp.Core.OptionModule.Map|[T,TResult|](FSharpFunc`2 mapping, FSharpOption`1 option)   at FSharp.MetadataFormat.ValueReader.readMemberOrVal(ReadingContext ctx, FSharpMemberFunctionOrValue v) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 340   at FSharp.MetadataFormat.Reader.tryReadMember@512.Invoke(String cat, IDictionary`2 _arg1, Comment comment) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 513   at FSharp.MetadataFormat.Reader.readCommentsInto|[a|](ReadingContext ctx, String xmlDoc, FSharpFunc`2 f) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 498   at FSharp.MetadataFormat.Reader.tryReadMember(ReadingContext ctx, MemberKind kind, FSharpMemberFunctionOrValue memb) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 512   at FSharp.MetadataFormat.Reader.readMembers@525.Invoke(FSharpMemberFunctionOrValue memb) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 525   at Microsoft.FSharp.Collections.IEnumerator.choose@163.System-Collections-IEnumerator-MoveNext()   at Microsoft.FSharp.Collections.SeqModule.ToList|[T|](IEnumerable`1 source)   at FSharp.MetadataFormat.Reader.readModule@606.Invoke(String cat, IDictionary`2 cmd, Comment comment) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 610   at FSharp.MetadataFormat.Reader.readCommentsInto|[a|](ReadingContext ctx, String xmlDoc, FSharpFunc`2 f) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 498   at FSharp.MetadataFormat.Reader.readModule(ReadingContext ctx, FSharpEntity modul) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 606   at FSharp.MetadataFormat.Reader.readModulesAndTypes@555.Invoke(ReadingContext ctx, FSharpEntity modul) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 555   at Microsoft.FSharp.Collections.IEnumerator.choose@163.System-Collections-IEnumerator-MoveNext()   at Microsoft.FSharp.Collections.SeqModule.ToList|[T|](IEnumerable`1 source)   at FSharp.MetadataFormat.Reader.readModulesAndTypes(ReadingContext ctx, IEnumerable`1 entities) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 557   at FSharp.MetadataFormat.Reader.readNamespace(ReadingContext ctx, String ns, IEnumerable`1 entities) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 627   at FSharp.MetadataFormat.Reader.namespaces@648.Invoke(Tuple`2 tupledArg) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 648   at Microsoft.FSharp.Collections.IEnumerator.map@116.DoMoveNext(b& )   at Microsoft.FSharp.Collections.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()   at Microsoft.FSharp.Collections.SeqModule.ToList|[T|](IEnumerable`1 source)   at FSharp.MetadataFormat.Reader.readAssembly(FSharpAssembly assembly, Boolean publicOnly, String xmlFile, FSharpOption`1 sourceFolderRepo) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 643   at <StartupCode$FSharp-MetadataFormat>.$Main.assemblies@753-2.GenerateNext(IEnumerable`1& next) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 765   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()   at Microsoft.FSharp.Collections.SeqModule.ToList|[T|](IEnumerable`1 source)   at FSharp.MetadataFormat.MetadataFormat.Generate(FSharpList`1 dllFiles, String outDir, IEnumerable`1 layoutRoots, FSharpOption`1 parameters, FSharpOption`1 namespaceTemplate, FSharpOption`1 moduleTemplate, FSharpOption`1 typeTemplate, FSharpOption`1 xmlFile, FSharpOption`1 sourceRepo, FSharpOption`1 sourceFolder, FSharpOption`1 publicOnly, FSharpOption`1 libDirs, FSharpOption`1 otherFlags) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 753   at FSharp.MetadataFormat.MetadataFormat.Generate(String dllFile, String outDir, IEnumerable`1 layoutRoots, FSharpOption`1 parameters, FSharpOption`1 namespaceTemplate, FSharpOption`1 moduleTemplate, FSharpOption`1 typeTemplate, FSharpOption`1 xmlFile, FSharpOption`1 sourceRepo, FSharpOption`1 sourceFolder, FSharpOption`1 publicOnly, FSharpOption`1 libDirs, FSharpOption`1 otherFlags) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 672   at FSI_0001.MakeManual.BuildContent@103.Invoke(Document doc) in C:\BuildAgent\work\9cca5f94ac237474\doc\MakeManual.fsx:line 103   at Microsoft.FSharp.Collections.SeqModule.Iterate|[T|](FSharpFunc`2 action, IEnumerable`1 source)   at FSI_0001.MakeManual.BuildContent@103.Invoke(Document doc) in C:\BuildAgent\work\9cca5f94ac237474\doc\MakeManual.fsx:line 103   at Microsoft.FSharp.Collections.SeqModule.Iterate|[T|](FSharpFunc`2 action, IEnumerable`1 source)   at FSI_0002.clo@73-9.Invoke(Unit _arg7) in C:\BuildAgent\work\9cca5f94ac237474\build.fsx:line 74   at Fake.TargetHelper.runTarget@290(String targetName)']
    [17:20:45]W:     [Step 2/2]    at Microsoft.FSharp.Core.OptionModule.Map[T,TResult](FSharpFunc`2 mapping, FSharpOption`1 option)
    [17:20:45]W:     [Step 2/2]    at FSharp.MetadataFormat.ValueReader.readMemberOrVal(ReadingContext ctx, FSharpMemberFunctionOrValue v) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 340
    [17:20:45]W:     [Step 2/2]    at FSharp.MetadataFormat.Reader.tryReadMember@512.Invoke(String cat, IDictionary`2 _arg1, Comment comment) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 513
    [17:20:45]W:     [Step 2/2]    at FSharp.MetadataFormat.Reader.readCommentsInto[a](ReadingContext ctx, String xmlDoc, FSharpFunc`2 f) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 498
    [17:20:45]W:     [Step 2/2]    at FSharp.MetadataFormat.Reader.tryReadMember(ReadingContext ctx, MemberKind kind, FSharpMemberFunctionOrValue memb) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 512
    [17:20:45]W:     [Step 2/2]    at FSharp.MetadataFormat.Reader.readMembers@525.Invoke(FSharpMemberFunctionOrValue memb) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 525
    [17:20:45]W:     [Step 2/2]    at Microsoft.FSharp.Collections.IEnumerator.choose@163.System-Collections-IEnumerator-MoveNext()
    [17:20:45]W:     [Step 2/2]    at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
    [17:20:45]W:     [Step 2/2]    at FSharp.MetadataFormat.Reader.readModule@606.Invoke(String cat, IDictionary`2 cmd, Comment comment) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 610
    [17:20:45]W:     [Step 2/2]    at FSharp.MetadataFormat.Reader.readCommentsInto[a](ReadingContext ctx, String xmlDoc, FSharpFunc`2 f) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 498
    [17:20:45]W:     [Step 2/2]    at FSharp.MetadataFormat.Reader.readModule(ReadingContext ctx, FSharpEntity modul) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 606
    [17:20:45]W:     [Step 2/2]    at FSharp.MetadataFormat.Reader.readModulesAndTypes@555.Invoke(ReadingContext ctx, FSharpEntity modul) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 555
    [17:20:45]W:     [Step 2/2]    at Microsoft.FSharp.Collections.IEnumerator.choose@163.System-Collections-IEnumerator-MoveNext()
    [17:20:45]W:     [Step 2/2]    at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
    [17:20:45]W:     [Step 2/2]    at FSharp.MetadataFormat.Reader.readModulesAndTypes(ReadingContext ctx, IEnumerable`1 entities) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 557
    [17:20:45]W:     [Step 2/2]    at FSharp.MetadataFormat.Reader.readNamespace(ReadingContext ctx, String ns, IEnumerable`1 entities) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 627
    [17:20:45]W:     [Step 2/2]    at FSharp.MetadataFormat.Reader.namespaces@648.Invoke(Tuple`2 tupledArg) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 648
    [17:20:45]W:     [Step 2/2]    at Microsoft.FSharp.Collections.IEnumerator.map@116.DoMoveNext(b& )
    [17:20:45]W:     [Step 2/2]    at Microsoft.FSharp.Collections.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
    [17:20:45]W:     [Step 2/2]    at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
    [17:20:45]W:     [Step 2/2]    at FSharp.MetadataFormat.Reader.readAssembly(FSharpAssembly assembly, Boolean publicOnly, String xmlFile, FSharpOption`1 sourceFolderRepo) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 643
    [17:20:45]W:     [Step 2/2]    at <StartupCode$FSharp-MetadataFormat>.$Main.assemblies@753-2.GenerateNext(IEnumerable`1& next) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 765
    [17:20:45]W:     [Step 2/2]    at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
    [17:20:45]W:     [Step 2/2]    at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
    [17:20:45]W:     [Step 2/2]    at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
    [17:20:45]W:     [Step 2/2]    at FSharp.MetadataFormat.MetadataFormat.Generate(FSharpList`1 dllFiles, String outDir, IEnumerable`1 layoutRoots, FSharpOption`1 parameters, FSharpOption`1 namespaceTemplate, FSharpOption`1 moduleTemplate, FSharpOption`1 typeTemplate, FSharpOption`1 xmlFile, FSharpOption`1 sourceRepo, FSharpOption`1 sourceFolder, FSharpOption`1 publicOnly, FSharpOption`1 libDirs, FSharpOption`1 otherFlags) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 753
    [17:20:45]W:     [Step 2/2]    at FSharp.MetadataFormat.MetadataFormat.Generate(String dllFile, String outDir, IEnumerable`1 layoutRoots, FSharpOption`1 parameters, FSharpOption`1 namespaceTemplate, FSharpOption`1 moduleTemplate, FSharpOption`1 typeTemplate, FSharpOption`1 xmlFile, FSharpOption`1 sourceRepo, FSharpOption`1 sourceFolder, FSharpOption`1 publicOnly, FSharpOption`1 libDirs, FSharpOption`1 otherFlags) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 672
    [17:20:45]W:     [Step 2/2]    at FSI_0001.MakeManual.BuildContent@103.Invoke(Document doc) in C:\BuildAgent\work\9cca5f94ac237474\doc\MakeManual.fsx:line 103
    [17:20:45]W:     [Step 2/2]    at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
    [17:20:45]W:     [Step 2/2]    at FSI_0001.MakeManual.BuildContent@103.Invoke(Document doc) in C:\BuildAgent\work\9cca5f94ac237474\doc\MakeManual.fsx:line 103
    [17:20:45]W:     [Step 2/2]    at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
    [17:20:45]W:     [Step 2/2]    at FSI_0002.clo@73-9.Invoke(Unit _arg7) in C:\BuildAgent\work\9cca5f94ac237474\build.fsx:line 74
    [17:20:45]W:     [Step 2/2]    at Fake.TargetHelper.runTarget@290(String targetName)

**Comment by tpetricek** [comment]
I'm closing this as it is quite old, but if this still happens with the latest version, please reopen it!

**Comment by koenmetsu** [comment]
Seeing this in 2.10.3 as well. 

Repro: 
```
git clone https://github.com/koenmetsu/Muffin.Pictures.Archiver.git
git checkout f3f9c11014248334eafa9d3aa2508aa64e29b9ce
build.cmd
```

**Comment by oscarvarto** [comment]
I think I am hitting this error in 2017, for version 2.14.4. See also https://github.com/fsprojects/ProjectScaffold/issues/309
