### ISSUE TITLE
CommandLine tool doesn't find dll, FAKE tool fails with InvalidOperationException

### ISSUE THREAD

**Issue by haf** [tpetricek/FSharp.Formatting#167]
Windows 

```
PS X:\logary\src\Logary\bin\Release> ../../../../buildsupport/FSharp.Formatting.CommandTool/tools/fsformatting.exe metadataFormat "--generat
e" "--dllFiles" Intelliplan.Logary.dll "--outDir" output "--layoutRoots" layouts
[0 sec] Resolving assembly: FSharp.Compiler.Service.resources, Version=0.0.44.0, Culture=en-US, PublicKeyToken=null
[0 sec] Resolving assembly: FSharp.Compiler.Service.resources, Version=0.0.44.0, Culture=en-US, PublicKeyToken=null
[0 sec] Resolving assembly: FSharp.Compiler.Service.resources, Version=0.0.44.0, Culture=en, PublicKeyToken=null
[0 sec] Resolving assembly: FSharp.Compiler.Service.resources, Version=0.0.44.0, Culture=en, PublicKeyToken=null
[2 sec] Resolving assembly: FSharp.Compiler.Service.resources, Version=0.0.44.0, Culture=en-US, PublicKeyToken=null
[2 sec] Resolving assembly: FSharp.Compiler.Service.resources, Version=0.0.44.0, Culture=en-US, PublicKeyToken=null
[2 sec] Resolving assembly: FSharp.Compiler.Service.resources, Version=0.0.44.0, Culture=en, PublicKeyToken=null
[2 sec] Resolving assembly: FSharp.Compiler.Service.resources, Version=0.0.44.0, Culture=en, PublicKeyToken=null
[5 sec] **** error: Could not resolve this reference. Could not locate the assembly "Intelliplan.Logary.dll". Check to make sure the assembl
y exists on disk. If this reference is required by your code, you may get compilation errors. (Code=MSB3245)
[5 sec] **** warning: Assembly reference 'Intelliplan.Logary.dll' was not found or is invalid
[5 sec] Reading assembly: Intelliplan.Logary.dll
[5 sec] **** Skipping assembly 'Intelliplan.Logary' because was not found in resolved assembly list
[0 sec] received exception in MetadataFormat.Generate:
 System.Exception: Unknown project name. Provide 'properties' parameter with 'project-name' key.
   at FSharp.MetadataFormat.MetadataFormat.Generate(FSharpList`1 dllFiles, String outDir, IEnumerable`1 layoutRoots, FSharpOption`1 paramete
rs, FSharpOption`1 namespaceTemplate, FSharpOption`1 moduleTemplate, FSharpOption`1 typeTemplate, FSharpOption`1 xmlFile, FSharpOption`1 sou
rceRepo, FSharpOption`1 sourceFolder, FSharpOption`1 publicOnly, FSharpOption`1 libDirs, FSharpOption`1 otherFlags, FSharpOption`1 markDownC
omments) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 830
   at FSharp.Formatting.Options.MetadataFormat.GenerateOptions.FSharp-Formatting-IExecutable-IExecutable-Execute() in c:\Tomas\Public\FSharp
.Formatting\src\FSharp.Formatting.CommandTool\OptionsMetadataFormat.fs:line 101
PS X:\logary\src\Logary\bin\Release> ls Intelliplan.Logary.dll


    Directory: X:\logary\src\Logary\bin\Release


Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-----        2014-06-05     09:17     256512 Intelliplan.Logary.dll
```

OS X:

```
16:27:47 ~/dev/logary/src/Logary/bin/Release $ mono ../../../../buildsupport/FSharp.Formatting.CommandTool/tools/fsformatting.exe metadataFormat "--generate" "--dllFiles" Intelliplan.Logary.dll "--outDir" output "--layoutRoots" layouts --libDirs .
[0 sec] Resolving assembly: FSharp.Compiler.Service.resources, Version=0.0.44.0, Culture=sv-SE, PublicKeyToken=null
[0 sec] Resolving assembly: FSharp.Compiler.Service.resources, Version=0.0.44.0, Culture=sv, PublicKeyToken=null
[0 sec] Resolving assembly: FSharp.Compiler.Service.resources, Version=0.0.44.0, Culture=sv-SE, PublicKeyToken=null
[0 sec] Resolving assembly: FSharp.Compiler.Service.resources, Version=0.0.44.0, Culture=sv, PublicKeyToken=null
[1 sec] **** error: Unable to find the file 'Intelliplan.Logary.dll' in any of
 /Library/Frameworks/Mono.framework/Versions/3.4.0/lib/mono/4.5
 /var/folders/j7/wbmqw81j2_jcfwn6_hh0ltlh4zjfkz/T/.
 /var/folders/j7/wbmqw81j2_jcfwn6_hh0ltlh4zjfkz/T
 /Library/Frameworks/Mono.framework/Versions/3.4.0/lib/mono/4.0
[1 sec] **** warning: Assembly reference 'Intelliplan.Logary.dll' was not found or is invalid
[1 sec] Reading assembly: Intelliplan.Logary.dll
[1 sec] **** Skipping assembly 'Intelliplan.Logary' because was not found in resolved assembly list
[0 sec] received exception in MetadataFormat.Generate:
 System.Exception: Unknown project name. Provide 'properties' parameter with 'project-name' key.
  at FSharp.MetadataFormat.MetadataFormat.Generate (Microsoft.FSharp.Collections.FSharpList`1 dllFiles, System.String outDir, IEnumerable`1 layoutRoots, Microsoft.FSharp.Core.FSharpOption`1 parameters, Microsoft.FSharp.Core.FSharpOption`1 namespaceTemplate, Microsoft.FSharp.Core.FSharpOption`1 moduleTemplate, Microsoft.FSharp.Core.FSharpOption`1 typeTemplate, Microsoft.FSharp.Core.FSharpOption`1 xmlFile, Microsoft.FSharp.Core.FSharpOption`1 sourceRepo, Microsoft.FSharp.Core.FSharpOption`1 sourceFolder, Microsoft.FSharp.Core.FSharpOption`1 publicOnly, Microsoft.FSharp.Core.FSharpOption`1 libDirs, Microsoft.FSharp.Core.FSharpOption`1 otherFlags, Microsoft.FSharp.Core.FSharpOption`1 markDownComments) [0x00000] in <filename unknown>:0
  at FSharp.Formatting.Options.MetadataFormat.GenerateOptions.FSharp-Formatting-IExecutable-IExecutable-Execute () [0x00000] in <filename unknown>:0
```

**Comment by haf** [comment]
@tpetricek do you know if F# Formatting works on mono with F# now?

**Comment by tpetricek** [comment]
I think we're waiting for final release of new RazorEngine, but the version from @matthid in PR #240 should work. Can we test this in your continuous build?

**Comment by tpetricek** [comment]
I was successfully able to use the most recent version on mono (with the improvements from @matthid).

@haf Could you try the most recent version again?

**Comment by forki** [comment]
Is there a tl;dr?. What should I do?

**Comment by haf** [comment]
@tpetricek WIP https://github.com/SuaveIO/suave/pull/225 and discussion: https://github.com/SuaveIO/suave/issues/223 -- currently too swamped to try it

**Comment by tpetricek** [comment]
@forki - I don't think you need to do anything here :-). Not sure how you got mentioned in this thread...?

@haf - Cool. I posted some comments on that PR.

**Comment by matthid** [comment]
I think we should either remove the command line tool (is anyone using that?) or add some tests for it.

**Comment by haf** [comment]
@matthid We want to use it; we are not using FAKE.

**Comment by haf** [comment]
Are there any docs for how to pass parameters to CommandTool besides reading source or the help output that doesn't tell you what's wrong?

**Comment by haf** [comment]
Ignore last comment; found docs had been improved a lot! https://tpetricek.github.io/FSharp.Formatting/commandline.html

**Comment by haf** [comment]
I think this issue is solved by now :) Thanks for fixing it!

**Comment by 64J0** [comment]
Hello people, I'm getting this error:

```
System.Exception: Unknown project name. Provide 'properties' parameter with 'project-name' key.
   at FSharp.MetadataFormat.MetadataFormat.Generate(IEnumerable`1 dllFiles, FSharpOption`1 parameters, FSharpOption`1 xmlFile, FSharpOption`1 sourceRepo, FSharpOption`1 sourceFolder, FSharpOption`1 publicOnly, FSharpOption`1 libDirs, FSharpOption`1 otherFlags, FSharpOption`1 markDownComments, FSharpOption`1 urlRangeHighlight) in /app/src/FSharp.MetadataFormat/Main.fs:line 1616
   at FSI_0019.Apirefloader.loader(String projectRoot, SiteContents siteContet)
```

But I'm not sure how to interpret it. How would you guys start debugging this?

I'm working in this PR:

* https://github.com/64J0/Saturn/pull/1
