### ISSUE TITLE
System.TypeLoadException: Inheritance security rules violated when running on CI server

### ISSUE THREAD

**Issue by Vidarls** [tpetricek/FSharp.Formatting#266]
```
System.TypeLoadException: Inheritance security rules violated by type: 'RazorEngine.Compilation.CSharp.CSharpRazorCodeLanguage'. Derived types must either match the security accessibility of the base type or be less accessible.
   at RazorEngine.Compilation.CSharp.CSharpDirectCompilerService..ctor(Boolean strictMode, Func`1 markupParserFactory)
   at RazorEngine.Compilation.DefaultCompilerServiceFactory.CreateCompilerService(Language language)
   at RazorEngine.Templating.RazorEngineCore.CreateTemplateType(ITemplateSource razorTemplate, Type modelType)
   at RazorEngine.Templating.RazorEngineCore.Compile(ITemplateKey key, Type modelType)
   at RazorEngine.Templating.RazorEngineService.CompileAndCacheInternal(ITemplateKey key, Type modelType)
   at RazorEngine.Templating.RazorEngineService.GetCompiledTemplate(ITemplateKey key, Type modelType, Boolean compileOnCacheMiss)
   at RazorEngine.Templating.RazorEngineService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.DynamicWrapperService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
   at RazorEngine.Templating.RazorEngineServiceExtensions.<>c__DisplayClass4.<RunCompile>b__3(TextWriter writer)
   at RazorEngine.Templating.RazorEngineServiceExtensions.WithWriter(Action`1 withWriter)
   at RazorEngine.Templating.RazorEngineServiceExtensions.RunCompile(IRazorEngineService service, String name, Type modelType, Object model, DynamicViewBag viewBag)
   at <StartupCode$FSharp-Literate>.$Razor.ProcessFileModel@130.Invoke(Unit _arg1) in c:\Tomas\Public\FSharp.Formatting\src\Common\Razor.fs:line 131
   at FSharp.Literate.RazorRender.handleCompile[a](String source, FSharpFunc`2 f) in c:\Tomas\Public\FSharp.Formatting\src\Common\Razor.fs:line 95
   at FSharp.Literate.RazorRender.ProcessFileModel[b](Type modelType, Object model, FSharpOption`1 properties) in c:\Tomas\Public\FSharp.Formatting\src\Common\Razor.fs:line 130
   at FSharp.Literate.Templating.generateFile(FSharpOption`1 references, String contentTag, IEnumerable`1 parameters, FSharpOption`1 templateOpt, String output, IEnumerable`1 layoutRoots) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.Literate\Formatting.fs:line 83
   at FSharp.Literate.Templating.processFile(FSharpOption`1 references, LiterateDocument doc, String output, ProcessingContext ctx) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.Literate\Formatting.fs:line 128
   at FSharp.Literate.Literate.ProcessMarkdown(String input, FSharpOption`1 templateFile, FSharpOption`1 output, FSharpOption`1 format, FSharpOption`1 formatAgent, FSharpOption`1 prefix, FSharpOption`1 compilerOptions, FSharpOption`1 lineNumbers, FSharpOption`1 references, FSharpOption`1 replacements, FSharpOption`1 includeSource, FSharpOption`1 layoutRoots, FSharpOption`1 generateAnchors, FSharpOption`1 assemblyReferences) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.Literate\Main.fs:line 140
   at <StartupCode$FSharp-Literate>.$Main.processMarkdown@173.Invoke(String file, String output) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.Literate\Main.fs:line 173
   at <StartupCode$FSharp-Literate>.$Main.processDirectory@180(FSharpOption`1 format, Boolean processRecursive, FSharpFunc`2 processScriptFile, FSharpFunc`2 processMarkdown, String indir, String outdir) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.Literate\Main.fs:line 199
   at FSharp.Literate.Literate.ProcessDirectory(String inputDirectory, FSharpOption`1 templateFile, FSharpOption`1 outputDirectory, FSharpOption`1 format, FSharpOption`1 formatAgent, FSharpOption`1 prefix, FSharpOption`1 compilerOptions, FSharpOption`1 lineNumbers, FSharpOption`1 references, FSharpOption`1 fsiEvaluator, FSharpOption`1 replacements, FSharpOption`1 includeSource, FSharpOption`1 layoutRoots, FSharpOption`1 generateAnchors, FSharpOption`1 assemblyReferences, FSharpOption`1 processRecursive) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.Literate\Main.fs:line 164

```

I assume this is somehow related to upgrading the Razor engine, as my old builds (running older versions of FSharp.formatting) does not have this issue.

Also: I have no issues running this on my dev machine, so I guess it has something to do with a more rigorous setup on a Server 2008 installation like the one the CI server is running on.

**Comment by matthid** [comment]
You are correct it is related to upgrading RazorEngine.
This usually happens if you use the .net45 build of RazorEngine with Razor2 or the .net40 build with Razor3. There is not much RazorEnine can do (because the underlaying problem is that Razor3 and Razor2 are build differently). Can you make sure that *correct* and *compatible* versions are loaded at runtime? The most likely reason is that you updated to Razor3 but you have a `#load "packages/RazorEngine/net40/RazorEngine.dll"` hanging around somewhere...

**Comment by Vidarls** [comment]
It does not seem like I have any loads hanging around.

I am running a buildscript from a slightly modified project scaffold. Pretty much like this: https://github.com/Vidarls/ProjectScaffold/blob/multiproject/build.template
with this as the driver of Fsharp.Formattin:
https://github.com/Vidarls/ProjectScaffold/blob/multiproject/docs/tools/generate.template

**Comment by Vidarls** [comment]
Depenencies:

```
NUGET
  remote: https://nuget.org/api/v2
  specs:
    FAKE (3.17.0)
    FSharp.Compiler.Service (0.0.82)
    FSharp.Formatting (2.7.4)
      FSharp.Compiler.Service (>= 0.0.82)
      FSharpVSPowerTools.Core (>= 1.7.0)
    FSharpVSPowerTools.Core (1.7.0)
      FSharp.Compiler.Service (>= 0.0.81)
    Microsoft.Bcl (1.1.9)
      Microsoft.Bcl.Build (>= 1.0.14)
    Microsoft.Bcl.Build (1.0.21)
    Microsoft.Net.Http (2.2.28)
      Microsoft.Bcl (>= 1.1.9)
      Microsoft.Bcl.Build (>= 1.0.14)
    NuGet.CommandLine (2.8.3)
    NUnit (2.6.4)
    NUnit.Runners (2.6.4)
    Octokit (0.6.2)
      Microsoft.Net.Http
    SourceLink.Fake (0.4.2)
GITHUB
  remote: fsharp/FAKE
  specs:
    modules/Octokit/Octokit.fsx (412ed0da4a9a8635e243e2ea06cf654ca805f6d8)
      Octokit


````

**Comment by Vidarls** [comment]
Anyways, should not a version conflict cause fail on both CI server and Dev machine?

**Comment by matthid** [comment]
CI is mono and mono doesn't enforce CAS.

**Comment by Vidarls** [comment]
Currently it is OK on my win 8.1 dev machine
not on my server 2008 r2 CI machine

**Comment by Vidarls** [comment]
Also the CI server on appveyor seems to have no issue, so might it be some setting on my 2008 machine, or are there underlaying issues that needs to be resolved?

**Comment by matthid** [comment]
strange, because the correct RazorEngine/Razor combination is actually bundled with FSharp.Formatting and it should work.. Is there a RazorEngine or Razor version in the GAC in your 2008 machine, maybe a wrong version is loaded from there? It would be more clear if you could somehow debug into or look which assemblies are actually loaded (http://stackoverflow.com/questions/4602912/how-to-debug-could-not-load-file-or-assembly-runtime-errors).

**Comment by Vidarls** [comment]
Everything seems to be in order.
It seems to be only loading the data from Fsharp.Formatting (though it is possible I misinterpret the sysinternals log..)

![dump](https://cloud.githubusercontent.com/assets/549092/6371758/fce6e6f2-bcfe-11e4-9b17-7cf2e7e06cbc.png)

**Comment by matthid** [comment]
Ah you are right, thanks for the analysis. I downloaded the nuget and in fact the wrong dlls are packaged in FSharp.Formatting (Razor3 and RazorEngine net40) not quite sure why though...

**Comment by matthid** [comment]
Somehow the net40 build slips into the `/bin` directory from where it get into the nuget package. This must be fixed, then it should work... You can test this by replacing the RazorEngine.dll with the one from the net45 folder (RazorEngine nuget package).

**Comment by matthid** [comment]
Ok the problem is here:
https://github.com/tpetricek/FSharp.Formatting/blob/master/src/FSharp.Markdown/FSharp.Markdown.fsproj#L13
https://github.com/tpetricek/FSharp.Formatting/blob/master/src/FSharp.MetadataFormat/FSharp.MetadataFormat.fsproj#L12
Updating only some projects to net45 is only possible when you stay on the net40 version of RazorEngine and Razor2 and that is difficult/impossible to do with Paket.

So the fix is to update all projects to net45.
Now thinking about it its weird how it would ever work on a windows machine or AppVeyor (there is only travis here on FSharp.Formatting!)...

**Comment by tpetricek** [comment]
It would be great to add AppVeryor, but somebody please tell me where to click :-).

@matthid If you can send a PR that updates the two projects, that would be amazing. Also, should we change the F# Formatting NuGet package so that the DLLs are in `lib/net45` rather than `lib/net40`?

**Comment by matthid** [comment]
renaming the folder doesn't really matter as long as the `#load` script stays up to date. Because we have gone the script way I would rather rename the folder to something like "tools" like FAKE does, or even release multiple nuget packages (one for script usage - which could bundle all references - and one to be referenced for programming).

**Comment by matthid** [comment]
@tpetricek : Adding AppVeyor should be as simple as copying appveyor.yml from ProjectScaffold, logging in to AppVeyor with your github account and Clicking "Add Project" to add FSharp.Formatting.

**Comment by forki** [comment]
http://fsprojects.github.io/ProjectScaffold/build-servers.html#AppVeyor

**Comment by nyousfi** [comment]
The solution to this problem for me (after wasting a whole day ) was to remove the Assembly Bindings in the web.config so removed the following as I needed Razor version 2.0.30506

<dependentAssembly>
<assemblyIdentity name="System.Web.Razor" publicKeyToken="31bf3856ad364e35" culture="neutral" />
<bindingRedirect oldVersion="0.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
</dependentAssembly>

**Comment by nyousfi** [comment]
The solution for me was to remove the following from the web.config.  I had a runtime assembly binding which was overriding my Razor version at runtime.

<dependentAssembly>
<assemblyIdentity name="System.Web.Razor" publicKeyToken="31bf3856ad364e35" culture="neutral" />
<bindingRedirect oldVersion="0.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
</dependentAssembly>

**Comment by nyousfi** [comment]
The solution for me was to remove the following from the web.config.  I had a runtime assembly binding which was overriding my Razor version at runtime.

`<dependentAssembly>
<assemblyIdentity name="System.Web.Razor" publicKeyToken="31bf3856ad364e35" culture="neutral" />
<bindingRedirect oldVersion="0.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
</dependentAssembly>`
