### ISSUE TITLE
error FS0192: internal error: null: GetTRefType

### ISSUE THREAD

**Issue by ovatsus** [tpetricek/FSharp.Formatting#272]
I never got this error before, but now when I call this bit of the F# Data docs generation script:

    Literate.ProcessDirectory
      ( dir, docTemplate, output @@ sub, replacements = ("root", root)::info,
        layoutRoots = layoutRoots, fsiEvaluator = fsiEvaluator )

I get this error

    error FS0192: internal error: null: GetTRefType

Get it both on VS2013 and VS2015. I tried to downgrade F# Formatting to previous version I used without issues, but now it doesn't work anymore. I have to idea of what's going on

Ideas?

**Comment by dungpa** [comment]
I think referencing `FSharpVSPowerTools.Core` should work e.g. https://github.com/fsprojects/ProjectScaffold/commit/29be5a01404a755755c90f1812c1c6b456cdf4d9 or https://github.com/fsprojects/Paket/commit/081bc56245eb9e97556000f94fd089a915b0cb49.

I think this is the same issue as https://github.com/tpetricek/FSharp.Formatting/issues/261.

**Comment by ovatsus** [comment]
Thanks, the reference fixed that issue, though now I have a bunch of other problems :/

I get these error messages in the middle of all the warnings:

      [2 sec] Error while building member-name for FSharp.Data.CsvRow because: the type '[]`1' does not have a qualified name
      [2 sec] Error while building member-name for FSharp.Data.HtmlDocumentExtensions.Descendants because: not a named type
      [2 sec] Error while building member-name for FSharp.Data.HtmlDocumentExtensions.Descendants because: not a named type
      [2 sec] Error while building member-name for FSharp.Data.HtmlDocumentExtensions.DescendantsWithPath because: not a named type
      [2 sec] Error while building member-name for FSharp.Data.HtmlDocumentExtensions.DescendantsWithPath because: not a named type
      [2 sec] Error while building member-name for FSharp.Data.TextConversions.AsFloat because: the type '[]`1' does not have a qualified name
      [2 sec] Error while building member-name for FSharp.Data.Runtime.JsonConversions.AsFloat because: the type '[]`1' does not have a qualified name
    
And then at the end I get this crash:

    System.InvalidCastException: The result type 'RazorEngine.Compilation.RazorDynamicObject' of the dynamic binding produced by the object with type 'RazorEngine.Compilation.RazorDynamicObject' for the binder 'Microsoft.CSharp.RuntimeBinder.CSharpConvertBinder' is not compatible with the result type 'FSharp.MetadataFormat.Type' expected by the call site.
       at CallSite.Target(Closure , CallSite , Object )
       at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
       at ActLike_IEnumerator`1_2514cc75195440fa9e6a5aaebbe5c7b3.get_Current()
       at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
       at CallSite.Target(Closure , CallSite , List`1 , Object )
       at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
       at CompiledRazorTemplates.Dynamic.RazorEngine_428c500878434cd6a28d8152bd48fb65.Execute() in c:\Git\FSharp.Data\docs\tools\templates\part-nested.cshtml:line 4
       at RazorEngine.Templating.TemplateBase.RazorEngine.Templating.ITemplate.Run(ExecuteContext context, TextWriter reader)
       at RazorEngine.Templating.TemplateBase.<>c__DisplayClass3.<Include>b__2(TextWriter tw)
       at RazorEngine.Templating.TemplateWriter.WriteTo(TextWriter writer)
       at RazorEngine.Templating.TemplateBase.Write(TemplateWriter helper)
       at CompiledRazorTemplates.Dynamic.RazorEngine_baf87a52e7974a3b8d986c4b0f2a4985.Execute() in c:\Git\FSharp.Data\packages\FSharp.Formatting\templates\reference\namespaces.cshtml:line 43
       at RazorEngine.Templating.TemplateBase.RazorEngine.Templating.ITemplate.Run(ExecuteContext context, TextWriter reader)
       at RazorEngine.Templating.RazorEngineCore.RunTemplate(ICompiledTemplate template, TextWriter writer, Object model, DynamicViewBag viewBag)
       at RazorEngine.Templating.RazorEngineService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
       at RazorEngine.Templating.DynamicWrapperService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
       at RazorEngine.Templating.RazorEngineServiceExtensions.<>c__DisplayClass4.<RunCompile>b__3(TextWriter writer)
       at RazorEngine.Templating.RazorEngineServiceExtensions.WithWriter(Action`1 withWriter)
       at RazorEngine.Templating.RazorEngineServiceExtensions.RunCompile(IRazorEngineService service, String name, Type modelType, Object model, DynamicViewBag viewBag)
       at <StartupCode$FSharp-MetadataFormat>.$Razor.ProcessFileModel@130.Invoke(Unit _arg1) in c:\Tomas\Public\FSharp.Formatting\src\Common\Razor.fs:line 131
       at FSharp.MetadataFormat.RazorRender.handleCompile[a](String source, FSharpFunc`2 f) in c:\Tomas\Public\FSharp.Formatting\src\Common\Razor.fs:line 95
       at FSharp.MetadataFormat.RazorRender.ProcessFileModel[b](Type modelType, Object model, FSharpOption`1 properties) in c:\Tomas\Public\FSharp.Formatting\src\Common\Razor.fs:line 130
       at FSharp.MetadataFormat.RazorRender`1.ProcessFile[a](model model, FSharpOption`1 properties) in c:\Tomas\Public\FSharp.Formatting\src\Common\Razor.fs:line 137
       at FSharp.MetadataFormat.MetadataFormat.Generate(FSharpList`1 dllFiles, String outDir, IEnumerable`1 layoutRoots, FSharpOption`1 parameters, FSharpOption`1 namespaceTemplate, FSharpOption`1 moduleTemplate, FSharpOption`1 typeTemplate, FSharpOption`1 xmlFile, FSharpOption`1 sourceRepo, FSharpOption`1 sourceFolder, FSharpOption`1 publicOnly, FSharpOption`1 libDirs, FSharpOption`1 otherFlags, FSharpOption`1 markDownComments, FSharpOption`1 urlRangeHighlight, FSharpOption`1 assemblyReferences) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 1128
       at <StartupCode$FSI_0002>.$FSI_0002.main@() in C:\Git\FSharp.Data\docs\tools\generate.fsx:line 144
    Stopped due to error

**Comment by dungpa** [comment]
Do you use the load script i.e. https://github.com/fsprojects/Paket/commit/081bc56245eb9e97556000f94fd089a915b0cb49? Hopefully @matthid can help with these issues.

**Comment by ovatsus** [comment]
Yes, I did: https://github.com/fsharp/FSharp.Data/commit/61aef22473f552d23ef33261fb0b003ddd3e47a2

**Comment by matthid** [comment]
I think this is basically the same root cause as https://github.com/Antaris/RazorEngine/issues/248. It is really hard to find a good default when anonymous types are involved (https://github.com/tpetricek/FSharp.Formatting/blob/master/misc/templates/reference/namespaces.cshtml#L46). The idea for the new recursive wrapping behavior was that we can now support "inner" anonymous classes, but a wrapper can only do so much... when you start using concrete types in the middle it will break apart... Its actually a bit hidden in the template:

 - Model is a wrapper
 - Model.Types is a wrapper
 - typesAndModules.AddRange expects an `IEnumerable<object>`
 - Model.Types doesn't implement `IEnumerable<object>` however we return a wrapper anyway (because we support casting to interfaces in the hope that the underlaying object implements it, or at least has all the members)
 - on the returned wrapper object the call to the property `Current` fails because the Current member with the expected signature doesn't exist.

This is really a *sick* edge case and the following should work:

```csharp
typesAndModules.AddRange((IEnumerable<FSharp.MetadataFormat.Type>)Model.Types);
typesAndModules.AddRange((IEnumerable<FSharp.MetadataFormat.Module>)Model.Modules);
```

Please try that and report back the results. Of course you can always stick to static types. I'm not sure if RazorEngine can ever perfectly support anonymous types. But as this is now the second time somebody is hit by this I'm thinking of changing back the defaults...

**Comment by ovatsus** [comment]
Tried replacing lines 4 and 5 in https://github.com/fsharp/FSharp.Data/blob/master/docs/tools/templates/part-nested.cshtml with this:

    typesAndModules.AddRange((IEnumerable<FSharp.MetadataFormat.Type>)Model.Types);
    typesAndModules.AddRange((IEnumerable<FSharp.MetadataFormat.Module>)Model.Modules);

But got same error:

    System.InvalidCastException: The result type 'RazorEngine.Compilation.RazorDynamicObject' of the dynamic binding produced by the object with type 'RazorEngine.Compilation.RazorDynamicObject' for the binder 'Microsoft.CSharp.RuntimeBinder.CSharpConvertBinder' is not compatible with the result type 'FSharp.MetadataFormat.Type' expected by the call site.
    >    at CallSite.Target(Closure , CallSite , Object )
       at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
       at ActLike_IEnumerator`1_595e3c03faf64c8c83ccbf016e2b3e1a.get_Current()
       at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
       at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
       at CompiledRazorTemplates.Dynamic.RazorEngine_762bacced35a4ab389ff7753ba4f1355.Execute() in c:\Git\FSharp.Data\docs\tools\templates\part-nested.cshtml:line 4
       at RazorEngine.Templating.TemplateBase.RazorEngine.Templating.ITemplate.Run(ExecuteContext context, TextWriter reader)
       at RazorEngine.Templating.TemplateBase.<>c__DisplayClass3.<Include>b__2(TextWriter tw)
       at RazorEngine.Templating.TemplateWriter.WriteTo(TextWriter writer)
       at RazorEngine.Templating.TemplateBase.Write(TemplateWriter helper)
       at CompiledRazorTemplates.Dynamic.RazorEngine_169a5a913d1d42c5a215c825b5296a17.Execute() in c:\Git\FSharp.Data\packages\FSharp.Formatting\templates\reference\namespaces.cshtml:line 43
       at RazorEngine.Templating.TemplateBase.RazorEngine.Templating.ITemplate.Run(ExecuteContext context, TextWriter reader)
       at RazorEngine.Templating.RazorEngineCore.RunTemplate(ICompiledTemplate template, TextWriter writer, Object model, DynamicViewBag viewBag)
       at RazorEngine.Templating.RazorEngineService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
       at RazorEngine.Templating.DynamicWrapperService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
       at RazorEngine.Templating.RazorEngineServiceExtensions.<>c__DisplayClass4.<RunCompile>b__3(TextWriter writer)
       at RazorEngine.Templating.RazorEngineServiceExtensions.WithWriter(Action`1 withWriter)
       at RazorEngine.Templating.RazorEngineServiceExtensions.RunCompile(IRazorEngineService service, String name, Type modelType, Object model, DynamicViewBag viewBag)
       at <StartupCode$FSharp-MetadataFormat>.$Razor.ProcessFileModel@130.Invoke(Unit _arg1) in c:\Tomas\Public\FSharp.Formatting\src\Common\Razor.fs:line 131
       at FSharp.MetadataFormat.RazorRender.handleCompile[a](String source, FSharpFunc`2 f) in c:\Tomas\Public\FSharp.Formatting\src\Common\Razor.fs:line 95
       at FSharp.MetadataFormat.RazorRender.ProcessFileModel[b](Type modelType, Object model, FSharpOption`1 properties) in c:\Tomas\Public\FSharp.Formatting\src\Common\Razor.fs:line 130
       at FSharp.MetadataFormat.RazorRender`1.ProcessFile[a](model model, FSharpOption`1 properties) in c:\Tomas\Public\FSharp.Formatting\src\Common\Razor.fs:line 137
       at FSharp.MetadataFormat.MetadataFormat.Generate(FSharpList`1 dllFiles, String outDir, IEnumerable`1 layoutRoots, FSharpOption`1 parameters, FSharpOption`1 namespaceTemplate, FSharpOption`1 moduleTemplate, FSharpOption`1 typeTemplate, FSharpOption`1 xmlFile, FSharpOption`1 sourceRepo, FSharpOption`1 sourceFolder, FSharpOption`1 publicOnly, FSharpOption`1 libDirs, FSharpOption`1 otherFlags, FSharpOption`1 markDownComments, FSharpOption`1 urlRangeHighlight, FSharpOption`1 assemblyReferences) in c:\Tomas\Public\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 1128
       at <StartupCode$FSI_0006>.$FSI_0006.main@() in C:\Git\FSharp.Data\docs\tools\generate.fsx:line 137
    Stopped due to error

**Comment by tpetricek** [comment]
Hmm, @matthid is the expert on RazorEngine-related things.

It looks as if the engine did not like something in some of the templates for generating API reference. Does F# Data use a customized version, or the default one?

**Comment by matthid** [comment]
Yeah scratch that I have a repro and I'm thinking about it if you want a "quick" fix you can either use static types or enumerate manually (with a foreach) instead of using AddRange

```csharp
foreach (var t in Model.Types) { typesAndModules.Add(t); }
```

this works in my repro case at least. I'm trying to fix the more general case at well but it seems to be really really ugly so I will need some time to think about it.

**Comment by ovatsus** [comment]
That worked, problem fixed. Thanks :)
https://github.com/fsharp/FSharp.Data/commit/96f49bf6ee100b68bf9eec69f8990184fd893c16

**Comment by tpetricek** [comment]
Do we need to do the same fix in the default F# Formatting templates?

**Comment by ovatsus** [comment]
This is a custom template. The default one has Modules and Types separated, but I preferred having them all together ordered alphabetically, as the difference between a type with static methods and a modules with functions is not that meaningful

**Comment by matthid** [comment]
You are welcome.
Actually I use F# formatting as some kind of additional integration test in RazorEngine so that shouldn't happen. If you ever drastically change them it would be nice to mention me so I can update the templates in the RazorEngine documentation generation as well.

So its quite unlikely that a RazorEngine version ships that breaks F#.Formatting as I'm using it for several projects now :).

**Comment by matthid** [comment]
By the way RazorEngine 3.6.2 should support that now... you are now able to use your original template. (Of course you need to wait a new F# formatting release as it is bundled there).

**Comment by matthid** [comment]
The `Error while building member-name for` errors mean that some member names could not be build and therefore you could get some "empty" entries in your documentation, besides that they shouldn't hurt. However they are printed out because they show FCS limitations (or members we should filter out somewhere along the line).

**Comment by ovatsus** [comment]
Thanks @matthid, next time I update the template I'll let you now
