### ISSUE TITLE
buildDocumentation fails

### ISSUE THREAD

**Issue by halcwb** [tpetricek/FSharp.Formatting#294]
Trying to run buildDocumentation in generate.fsx fails with:

Generating 'C:\Users\hal\Dropbox\Development\GenPres\docs\tools\..\content/index.html'
System.TypeLoadException: Method 'get_LineCount' in type 'lexer@289' from assembly 'FSharp.CodeFormat, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at FSharp.CodeFormat.CodeFormatAgent.ParseSource(String file, String source, FSharpOption`1 options, FSharpOption`1 defines) in c:\Tomas\FSharp.Formatting\src\FSharp.CodeFormat\CodeFormatAgent.fs:line 389
   at FSharp.Literate.ParseScript.parseScriptFile(String file, String content, CompilerContext ctx) in c:\Tomas\FSharp.Formatting\src\FSharp.Literate\ParseScript.fs:line 197
   at FSharp.Literate.Literate.ParseScriptFile[d](String path, FSharpOption`1 formatAgent, FSharpOption`1 compilerOptions, FSharpOption`1 definedSymbols, FSharpOption`1 references, FSharpOption`1 fsiEvaluator) in c:\Tomas\FSharp.Formatting\src\FSharp.Literate\Main.fs:line 62
   at FSharp.Literate.Literate.ProcessScriptFile(String input, FSharpOption`1 templateFile, FSharpOption`1 output, FSharpOption`1 format, FSharpOption`1 formatAgent, FSharpOption`1 prefix, FSharpOption`1 compilerOptions, FSharpOption`1 lineNumbers, FSharpOption`1 references, FSharpOption`1 fsiEvaluator, FSharpOption`1 replacements, FSharpOption`1 includeSource, FSharpOption`1 layoutRoots, FSharpOption`1 generateAnchors, FSharpOption`1 assemblyReferences) in c:\Tomas\FSharp.Formatting\src\FSharp.Literate\Main.fs:line 152
   at <StartupCode$FSharp-Literate>.$Main.processScriptFile@167.Invoke(String file, String output) in c:\Tomas\FSharp.Formatting\src\FSharp.Literate\Main.fs:line 167
   at <StartupCode$FSharp-Literate>.$Main.processDirectory@180(FSharpOption`1 format, Boolean processRecursive, FSharpFunc`2 processScriptFile, FSharpFunc`2 processMarkdown, String indir, String outdir) in c:\Tomas\FSharp.Formatting\src\FSharp.Literate\Main.fs:line 198
   at FSharp.Literate.Literate.ProcessDirectory(String inputDirectory, FSharpOption`1 templateFile, FSharpOption`1 outputDirectory, FSharpOption`1 format, FSharpOption`1 formatAgent, FSharpOption`1 prefix, FSharpOption`1 compilerOptions, FSharpOption`1 lineNumbers, FSharpOption`1 references, FSharpOption`1 fsiEvaluator, FSharpOption`1 replacements, FSharpOption`1 includeSource, FSharpOption`1 layoutRoots, FSharpOption`1 generateAnchors, FSharpOption`1 assemblyReferences, FSharpOption`1 processRecursive) in c:\Tomas\FSharp.Formatting\src\FSharp.Literate\Main.fs:line 164
   at FSI_0004.buildDocumentation() in C:\Users\hal\Dropbox\Development\GenPres\docs\tools\generate.fsx:line 123
   at <StartupCode$FSI_0007>.$FSI_0007.main@()
Stopped due to error
> 
Not sure what this error means.

**Comment by halcwb** [comment]
Probably it doesn't have a proper implementation of LexerBase. However, as far as I can tell all the dependencies are in place.

**Comment by matthid** [comment]
Try looking into #277.

**Comment by halcwb** [comment]
I did, I pinpointed the powertools version but still, no result:

NUGET
  remote: https://www.nuget.org/api/v2
  specs:
    AutoMapper (3.3.1)
    Deedle (1.0.6)
      FSharp.Data (2.0.14)
    Ext.Direct.Mvc4 (3.0.2)
      Microsoft.AspNet.Mvc (>= 4.0.20710.0)
      Newtonsoft.Json (>= 4.5.11)
    FAKE (3.27.5)
    Faker.Net (1.0.3)
    FsCheck (2.0.0)
      FSharp.Core (>= 3.1.2.1)
    FSharp.Compiler.Service (0.0.87)
    FSharp.Core (3.1.2.1)
    FSharp.Data (2.0.14)
      Zlib.Portable (>= 1.10.0) - framework: portable-net40+sl50+wp80+win80
    FSharp.Formatting (2.8.0)
      FSharp.Compiler.Service (>= 0.0.86)
      FSharpVSPowerTools.Core (>= 1.7.0)
    FSharpVSPowerTools.Core (1.8.0)
      FSharp.Compiler.Service (>= 0.0.87)

**Comment by matthid** [comment]
As the fix is not jet released (if I'm not mistaken) you need to use
```
nuget FSharpVSPowerTools.Core == 1.7.0
```
Currently you use `FSharpVSPowerTools.Core (1.8.0)`

**Comment by halcwb** [comment]
I tried both. However, I discovered that changing the paket dependency file is not enough, you also need to delete the lock file and then run the paket install again to get to the right package. Now, everything runs fine indeed. Thanks.

**Comment by matthid** [comment]
Good to hear :). Normally I run `paket update` after changing the dependency file.

**Comment by forki** [comment]
as described in the Paket issue. Running `paket install` should be enough, but I assume there is a bug.  I will try to fix it as soon as I get the data.

**Comment by matthid** [comment]
Oh, thanks for the clarification.

**Comment by forki** [comment]
the bug is fixed in Paket 0.41.3
