### ISSUE TITLE
Improve error message when Docs failed to build with an XML Parse error.

### ISSUE THREAD

**Issue by Rickasaurus** [tpetricek/FSharp.Formatting#335]
Error text follows, I'm having a very hard time figuring out what went wrong. It seems like it's digging into assemblies I'm not using at all.

```
Creating C:\Users\rminerich\Documents\GitHub\Fungible\docs\output\reference
Yaaf.FSharp.Scriping Warning: 0 : Parsing and checking warnings:
        **** error: Problem reading assembly '': Exception of type 'Microsoft.FS
harp.Compiler.ErrorLogger+InternalError' was thrown.
        **** error: internal error: PrepareToImportReferencedIlDll: cannot refer
ence .NET netmodules directly, reference the containing assembly instead
        **** error: Problem reading assembly '': Error opening binary file 'C:\P
rogram Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\S
ystem.EnterpriseServices.Thunk.dll': C:\Program Files (x86)\Reference Assemblies
\Microsoft\Framework\.NETFramework\v4.0\System.EnterpriseServices.Thunk.dll: bad
 cli header, rva 0
        **** error: Error opening binary file 'C:\Program Files (x86)\Reference
Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.EnterpriseServices.Thun
k.dll': C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFram
ework\v4.0\System.EnterpriseServices.Thunk.dll: bad cli header, rva 0
System.Xml.XmlException: Name cannot begin with the ''' character, hexadecimal v
alue 0x27. Line 159, position 81.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseQName(Boolean isQName, Int32 startOffset
, Int32& colonPos)
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at FSharp.MetadataFormat.Reader.readAssembly(FSharpAssembly assembly, Boolean
 publicOnly, String xmlFile, FSharpOption`1 sourceFolderRepo, FSharpFunc`2 urlRa
ngeHighlight, Boolean markDownComments, IUrlHolder urlMap, String codeFormatComp
ilerArgs) in c:\Tomas\Public\tpetricek\FSharp.Formatting\src\FSharp.MetadataForm
at\Main.fs:line 961
   at <StartupCode$FSharp-MetadataFormat>.$Main.assemblies@1118-2.Invoke(Tuple`2
 _arg2) in c:\Tomas\Public\tpetricek\FSharp.Formatting\src\FSharp.MetadataFormat
\Main.fs:line 1123
   at Microsoft.FSharp.Collections.ListModule.chooseAllAcc[a,b](FSharpFunc`2 f,
FSharpList`1 xs, FSharpList`1 acc)
   at FSharp.MetadataFormat.MetadataFormat.Generate(FSharpList`1 dllFiles, Strin
g outDir, FSharpList`1 layoutRoots, FSharpOption`1 parameters, FSharpOption`1 na
mespaceTemplate, FSharpOption`1 moduleTemplate, FSharpOption`1 typeTemplate, FSh
arpOption`1 xmlFile, FSharpOption`1 sourceRepo, FSharpOption`1 sourceFolder, FSh
arpOption`1 publicOnly, FSharpOption`1 libDirs, FSharpOption`1 otherFlags, FShar
pOption`1 markDownComments, FSharpOption`1 urlRangeHighlight, FSharpOption`1 ass
emblyReferences) in c:\Tomas\Public\tpetricek\FSharp.Formatting\src\FSharp.Metad
ataFormat\Main.fs:line 1118
   at <StartupCode$FSI_0003>.$FSI_0003.main@() in C:\Users\rminerich\Documents\G
itHub\Fungible\docs\tools\generate.fsx:line 140
Stopped due to error
Running build failed.
Error:
System.Exception: generating reference documentation failed
   at FSI_0001.Build.clo@185-19.Invoke(Unit _arg11)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake
\src\app\FakeLib\TargetHelper.fs:line 411
```

**Comment by Rickasaurus** [comment]
This is with FSharp.Formatting (2.10.0)

**Comment by Rickasaurus** [comment]
I managed to figure out the problem. Apparently in this line of the xml:
```<param name="propertyMap">A map of paths to types gotten from getPathsAndTypes<'t></param>```
the tick caused it to explode.

**Comment by eiriktsarpalis** [comment]
I've come across this problem quite a few times before. This is an issue of the F# compiler really, which does not detect xml doc parse errors.

**Comment by Rickasaurus** [comment]
In this case I think just a little extra debug information in the exception would have gone a long way.

**Comment by eiriktsarpalis** [comment]
True that.

**Comment by tpetricek** [comment]
Thanks for digging into the issue. We should certainly improve the error reporting.

How does the XML document end up looking like this? Shouldn't the F# compiler producing it escape everything properly?

**Comment by eiriktsarpalis** [comment]
@tpetricek The F# compiler will basically copy any text behind triple slashes verbatim to the assembly. Maybe we should file an issue with visualfsharp.

**Comment by tpetricek** [comment]
Hmm, I'd say that the compiler should always produce a valid XML....

**Comment by eiriktsarpalis** [comment]
:+1:

**Comment by evilz** [comment]
Same error with some C# projects.

Yaaf.FSharp.Scriping Warning: 0 : Parsing and checking warnings:
        **** error: Problem reading assembly '': Exception of type 'Microsoft.FSharp.Compiler.ErrorLogger+InternalError'
 was thrown.
        **** error: internal error: PrepareToImportReferencedIlDll: cannot reference .NET netmodules directly, reference
 the containing assembly instead
        **** error: Problem reading assembly '': Error opening binary file 'C:\Program Files (x86)\Reference Assemblies\
Microsoft\Framework\.NETFramework\v4.0\System.EnterpriseServices.Thunk.dll': C:\Program Files (x86)\Reference Assemblies
\Microsoft\Framework\.NETFramework\v4.0\System.EnterpriseServices.Thunk.dll: bad cli header, rva 0
        **** error: Error opening binary file 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFrame
work\v4.0\System.EnterpriseServices.Thunk.dll': C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFram
ework\v4.0\System.EnterpriseServices.Thunk.dll: bad cli header, rva 0
        **** error: Assembly reference 'C:\Users\Vincent\Documents\GITHUB\pathfinding\bin\Pathfinding.TestApp\Pathfindin
g.TestApp.dll' was not found or is invalid
Microsoft.FSharp.Compiler.ErrorLogger+ReportedError: The type 'ValueType' is required here and is unavailable. You must
add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

**Comment by tpetricek** [comment]
I have now seen this error in some projects that use F# Formatting too - it gets printed to the log, but then it continues and actually runs OK. I guess that's not the case here?

**Comment by matthid** [comment]
@evilz I think you encountered a different issue. Can you try 2.11.0-alpha1 and see if it fixes your issue (and open a separate issue if it doesn't).

**Comment by evilz** [comment]
Hi I tried, it's working now. I'm asking my self if it works on PCL or Core lib.If not I will create new issue.
Thank

**Comment by CumpsD** [comment]
I'm running into the same issue, you can repo it with this, target ```GenerateReferenceDocs```: https://github.com/exira/aws-s3-cache

```
[Step 1/3] Target: GenerateReferenceDocs
[00:34:56][Step 1/3] Help generated
[00:34:57][Step 1/3] FSharp.Formatting Information: 0 : FSharp.Formatting Logging setup!
[00:34:57][Step 1/3] Yaaf.FSharp.Scriping Information: 0 : Yaaf.FSharp.Scripting Logging setup!
[00:34:57][Step 1/3] Copying file: E:\TeamCityAgentWork\92d68a36015a96cc\docs\output\img\logo.png
[00:34:57][Step 1/3] Copying file: E:\TeamCityAgentWork\92d68a36015a96cc\docs\output\img\logobig.png
[00:34:57][Step 1/3] Copying styles and scripts: E:\TeamCityAgentWork\92d68a36015a96cc\docs\output\content\style.css
[00:34:57][Step 1/3] Copying styles and scripts: E:\TeamCityAgentWork\92d68a36015a96cc\docs\output\content\style_light.css
[00:34:57][Step 1/3] Copying styles and scripts: E:\TeamCityAgentWork\92d68a36015a96cc\docs\output\content\tips.js
[00:34:57][Step 1/3] Copying styles and scripts: E:\TeamCityAgentWork\92d68a36015a96cc\docs\output\content\img\github-blue.png
[00:34:57][Step 1/3] Copying styles and scripts: E:\TeamCityAgentWork\92d68a36015a96cc\docs\output\content\img\github.png
[00:34:57][Step 1/3] Creating E:\TeamCityAgentWork\92d68a36015a96cc\docs\output\reference
[00:35:01][Step 1/3] Yaaf.FSharp.Scriping Warning: 0 : Parsing and checking warnings: 
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\WorkflowServiceHostPerformanceCounters.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\WorkflowServiceHostPerformanceCounters.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\WorkflowServiceHostPerformanceCounters.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\WorkflowServiceHostPerformanceCounters.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\WMINet_Utils.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\WMINet_Utils.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\WMINet_Utils.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\WMINet_Utils.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\webengine4.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\webengine4.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\webengine4.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\webengine4.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\webengine.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\webengine.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\webengine.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\webengine.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\TLBREF.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\TLBREF.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\TLBREF.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\TLBREF.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\SOS.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\SOS.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\SOS.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\SOS.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\ServiceMonikerSupport.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\ServiceMonikerSupport.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\ServiceMonikerSupport.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\ServiceMonikerSupport.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\ServiceModelRegUI.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\ServiceModelRegUI.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\ServiceModelRegUI.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\ServiceModelRegUI.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\ServiceModelPerformanceCounters.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\ServiceModelPerformanceCounters.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\ServiceModelPerformanceCounters.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\ServiceModelPerformanceCounters.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\ServiceModelInstallRC.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\ServiceModelInstallRC.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\ServiceModelInstallRC.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\ServiceModelInstallRC.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\ServiceModelEvents.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\ServiceModelEvents.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\ServiceModelEvents.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\ServiceModelEvents.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\SbsNclPerf.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\SbsNclPerf.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\SbsNclPerf.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\SbsNclPerf.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\peverify.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\peverify.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\peverify.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\peverify.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\PerfCounter.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\PerfCounter.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\PerfCounter.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\PerfCounter.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorsvc.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorsvc.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorsvc.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorsvc.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorsn.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorsn.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorsn.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorsn.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorsecimpl.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorsecimpl.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorsecimpl.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorsecimpl.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorrc.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorrc.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorrc.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorrc.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorpehost.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorpehost.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorpehost.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorpehost.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorpe.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorpe.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorpe.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorpe.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscoreeis.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscoreeis.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscoreeis.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscoreeis.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscoreei.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscoreei.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscoreei.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscoreei.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscordbi.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscordbi.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscordbi.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscordbi.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscordacwks.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscordacwks.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscordacwks.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscordacwks.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\MmcAspExt.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\MmcAspExt.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\MmcAspExt.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\MmcAspExt.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\InstallUtilLib.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\InstallUtilLib.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\InstallUtilLib.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\InstallUtilLib.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\fusion.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\fusion.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\fusion.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\fusion.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\FileTracker.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\FileTracker.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\FileTracker.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\FileTracker.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\EventLogMessages.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\EventLogMessages.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\EventLogMessages.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\EventLogMessages.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\diasymreader.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\diasymreader.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\diasymreader.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\diasymreader.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\dfdll.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\dfdll.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\dfdll.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\dfdll.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\Culture.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\Culture.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\Culture.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\Culture.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\CORPerfMonExt.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\CORPerfMonExt.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\CORPerfMonExt.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\CORPerfMonExt.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\clrjit.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\clrjit.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\clrjit.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\clrjit.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\clretwrc.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\clretwrc.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\clretwrc.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\clretwrc.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\clrcompression.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\clrcompression.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\clrcompression.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\clrcompression.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\aspnet_rc.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\aspnet_rc.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\aspnet_rc.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\aspnet_rc.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\Aspnet_perf.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\Aspnet_perf.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\Aspnet_perf.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\Aspnet_perf.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\aspnet_isapi.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\aspnet_isapi.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\aspnet_isapi.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\aspnet_isapi.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\aspnet_filter.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\aspnet_filter.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\aspnet_filter.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\aspnet_filter.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\alink.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\alink.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\alink.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\alink.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Problem reading assembly '': Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\AdoNetDiag.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\AdoNetDiag.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Error opening binary file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\AdoNetDiag.dll': C:\Windows\Microsoft.NET\Framework\v4.0.30319\AdoNetDiag.dll: bad cli header, rva 0
[00:35:01][Step 1/3] 	**** error: Assembly reference 'E:\TeamCityAgentWork\92d68a36015a96cc\bin\aws-s3-cache\aws-s3-cache.dll' was not found or is invalid
[00:35:01][Step 1/3] FSharp.Formatting Warning: 0 : **** Skipping assembly 'E:\TeamCityAgentWork\92d68a36015a96cc\bin\aws-s3-cache\aws-s3-cache.dll' because was not found in resolved assembly list
[00:35:01][Step 1/3] FSharp.Formatting Information: 0 : Starting razor engine
[00:35:01][Step 1/3] FSharp.Formatting Information: 0 : Generating: index.html
[00:35:02][Step 1/3] FSharp.Formatting Information: 0 : Generating modules...
[00:35:02][Step 1/3] FSharp.Formatting Information: 0 : Generating types...
[00:35:03][Step 1/3] Finished Target: GenerateReferenceDocs
```

**Comment by CumpsD** [comment]
PS: Although the build continues, the output is empty: http://git.exira.com/aws-s3-cache/reference/index.html

**Comment by matthid** [comment]
Tracked in #370.
