### ISSUE TITLE
Build error on teamcity

### ISSUE THREAD

**Issue by forki** [tpetricek/FSharp.Formatting#34]
Hi,

I'm traying to put the use the MetadatFormat.Generate function on teamcity (see http://teamcity.codebetter.com/viewLog.html?buildId=87568&buildTypeId=bt166&tab=buildLog) but I get:

![image](https://f.cloud.github.com/assets/57396/1342328/0d9fa69e-3661-11e3-93b4-c07bfb13d316.png)

Running build failed.
[12:24:00][Step 2/2] Error:
[12:24:00][Step 2/2] System.TypeInitializationException: The type initializer for 'Microsoft.FSharp.Metadata.AssemblyLoader' threw an exception. ---> System.TypeInitializationException: The type initializer for '<StartupCode$FSharp-PowerPack-Metadata>.$Metadata' threw an exception. ---> System.ArgumentException: could not produce an FSharpAssembly object for the assembly 'FSharp.Core' because this is not an F# assembly
[12:24:00][Step 2/2] Parameter name: name
[12:24:00][Step 2/2]    at Microsoft.FSharp.Core.Operators.Raise[T](Exception exn)
[12:24:00][Step 2/2]    at Microsoft.FSharp.Metadata.AssemblyLoader.Add(String name, Assembly assembly) in C:\dev\FSharp.PowerPack\src\FSharp.PowerPack.Metadata\Metadata.fs:line 257
[12:24:00][Step 2/2]    at <StartupCode$FSharp-PowerPack-Metadata>.$Metadata..cctor() in C:\dev\FSharp.PowerPack\src\FSharp.PowerPack.Metadata\Metadata.fs:line 191
[12:24:00][Step 2/2]    --- End of inner exception stack trace ---
[12:24:00][Step 2/2]    at Microsoft.FSharp.Metadata.AssemblyLoader..cctor() in C:\dev\FSharp.PowerPack\src\FSharp.PowerPack.Metadata\Metadata.fs:line 0
[12:24:00][Step 2/2]    --- End of inner exception stack trace ---
[12:24:00][Step 2/2]    at Microsoft.FSharp.Metadata.AssemblyLoader.Get(Assembly assembly)
[12:24:00][Step 2/2]    at Microsoft.FSharp.Metadata.FSharpAssembly.FromAssembly(Assembly assembly) in C:\dev\FSharp.PowerPack\src\FSharp.PowerPack.Metadata\Metadata.fs:line 309
[12:24:00][Step 2/2]    at Microsoft.FSharp.Metadata.FSharpAssembly.FromFile(String fileName) in C:\dev\FSharp.PowerPack\src\FSharp.PowerPack.Metadata\Metadata.fs:line 314
[12:24:00][Step 2/2]    at FSharp.MetadataFormat.MetadataFormat.Generate(String dllFile, String outDir, String layoutRoot, FSharpOption`1 namespaceTemplate, FSharpOption`1 moduleTemplate, FSharpOption`1 typeTemplate, FSharpOption`1 xmlFile) in c:\dev\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 586
[12:24:00][Step 2/2]    at FSI_0001.clo@104-7.Invoke(Unit _arg5) in D:\BuildAgent-01\work\aa3eed2981961aa\build.fsx:line 115
[12:24:00][Step 2/2]    at Fake.TargetHelper.runTarget@259(String targetName) in D:\BuildAgent-01\work\aa3eed2981961aa\src\app\FakeLib\TargetHelper.fs:line 270
[12:24:00][Step 2/2] System.TypeInitializationException: The type initializer for 'Microsoft.FSharp.Metadata.AssemblyLoader' threw an exception. ---> System.TypeInitializationException: The type initializer for '<StartupCode$FSharp-PowerPack-Metadata>.$Metadata' threw an exception. ---> System.ArgumentException: could not produce an FSharpAssembly object for the assembly 'FSharp.Core' because this is not an F# assembly
[12:24:00][Step 2/2] Parameter name: name
[12:24:00][Step 2/2]    at Microsoft.FSharp.Core.Operators.Raise[T](Exception exn)
[12:24:00][Step 2/2]    at Microsoft.FSharp.Metadata.AssemblyLoader.Add(String name, Assembly assembly) in C:\dev\FSharp.PowerPack\src\FSharp.PowerPack.Metadata\Metadata.fs:line 257
[12:24:00][Step 2/2]    at <StartupCode$FSharp-PowerPack-Metadata>.$Metadata..cctor() in C:\dev\FSharp.PowerPack\src\FSharp.PowerPack.Metadata\Metadata.fs:line 191
[12:24:00][Step 2/2]    --- End of inner exception stack trace ---
[12:24:00][Step 2/2]    at Microsoft.FSharp.Metadata.AssemblyLoader..cctor() in C:\dev\FSharp.PowerPack\src\FSharp.PowerPack.Metadata\Metadata.fs:line 0
[12:24:00][Step 2/2]    --- End of inner exception stack trace ---
[12:24:00][Step 2/2]    at Microsoft.FSharp.Metadata.AssemblyLoader.Get(Assembly assembly)
[12:24:00][Step 2/2]    at Microsoft.FSharp.Metadata.FSharpAssembly.FromAssembly(Assembly assembly) in C:\dev\FSharp.PowerPack\src\FSharp.PowerPack.Metadata\Metadata.fs:line 309
[12:24:00][Step 2/2]    at Microsoft.FSharp.Metadata.FSharpAssembly.FromFile(String fileName) in C:\dev\FSharp.PowerPack\src\FSharp.PowerPack.Metadata\Metadata.fs:line 314
[12:24:00][Step 2/2]    at FSharp.MetadataFormat.MetadataFormat.Generate(String dllFile, String outDir, String layoutRoot, FSharpOption`1 namespaceTemplate, FSharpOption`1 moduleTemplate, FSharpOption`1 typeTemplate, FSharpOption`1 xmlFile) in c:\dev\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 586
[12:24:00][Step 2/2]    at FSI_0001.clo@104-7.Invoke(Unit _arg5) in D:\BuildAgent-01\work\aa3eed2981961aa\build.fsx:line 115
[12:24:00][Step 2/2]    at Fake.TargetHelper.runTarget@259(String targetName) in D:\BuildAgent-01\work\aa3eed2981961aa\src\app\FakeLib\TargetHelper.fs:line 270
[12:24:00][Step 2/2] ##teamcity[buildStatus status='FAILURE' text='System.TypeInitializationException: The type initializer for |'Microsoft.FSharp.Metadata.AssemblyLoader|' threw an exception. ---> System.TypeInitializationException: The type initializer for |'<StartupCode$FSharp-PowerPack-Metadata>.$Metadata|' threw an exception. ---> System.ArgumentException: could not produce an FSharpAssembly object for the assembly |'FSharp.Core|' because this is not an F# assemblyParameter name: name   at Microsoft.FSharp.Core.Operators.Raise|[T|](Exception exn)   at Microsoft.FSharp.Metadata.AssemblyLoader.Add(String name, Assembly assembly) in C:\dev\FSharp.PowerPack\src\FSharp.PowerPack.Metadata\Metadata.fs:line 257   at <StartupCode$FSharp-PowerPack-Metadata>.$Metadata..cctor() in C:\dev\FSharp.PowerPack\src\FSharp.PowerPack.Metadata\Metadata.fs:line 191   --- End of inner exception stack trace ---   at Microsoft.FSharp.Metadata.AssemblyLoader..cctor() in C:\dev\FSharp.PowerPack\src\FSharp.PowerPack.Metadata\Metadata.fs:line 0   --- End of inner exception stack trace ---   at Microsoft.FSharp.Metadata.AssemblyLoader.Get(Assembly assembly)   at Microsoft.FSharp.Metadata.FSharpAssembly.FromAssembly(Assembly assembly) in C:\dev\FSharp.PowerPack\src\FSharp.PowerPack.Metadata\Metadata.fs:line 309   at Microsoft.FSharp.Metadata.FSharpAssembly.FromFile(String fileName) in C:\dev\FSharp.PowerPack\src\FSharp.PowerPack.Metadata\Metadata.fs:line 314   at FSharp.MetadataFormat.MetadataFormat.Generate(String dllFile, String outDir, String layoutRoot, FSharpOption`1 namespaceTemplate, FSharpOption`1 moduleTemplate, FSharpOption`1 typeTemplate, FSharpOption`1 xmlFile) in c:\dev\FSharp.Formatting\src\FSharp.MetadataFormat\Main.fs:line 586   at FSI_0001.clo@104-7.Invoke(Unit _arg5) in D:\BuildAgent-01\work\aa3eed2981961aa\build.fsx:line 115   at Fake.TargetHelper.runTarget@259(String targetName) in D:\BuildAgent-01\work\aa3eed2981961aa\src\app\FakeLib\TargetHelper.fs:line 270']
[12:24:00][Step 2/2] 

I works locally on my machine.

Any ideas?

**Comment by dsyme** [comment]
This is so old it should be closed?

**Comment by tpetricek** [comment]
Very likely not an issue anymore, but @forki feel free to complain and we can get back to this.
